### ISSUE TITLE
Missing Swift version

### ISSUE THREAD

**Issue by blankey1337** [react-native-hero/picker#1]
Upon installation, I see this error during `pod install` phase:

[!] Unable to determine Swift version for the following pods:

- `HeroPicker` does not specify a Swift version and none of the targets (`[app name]`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by musicode** [comment]
Swift version is setted in `@react-native-hero/picker@0.0.8`.
